# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a6794c23cca71cbe8803de588f8e5f41c7f65f9eb88519e8d17211afc21b01f81a025b5e82a6a88a5a4278b9173d3e9caf6ee2822d8f37a801a621ff0a8273d

test:
  secret_key_base: 1fc4ff98e7c7cc7c30f0a212f9327ec9c4b58a8ed5588aef38e617dbc96ddc9498161ccd51d92435738f3a3461481c85445bd7b48df8d41cc61363194ab48f63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
